"""stage_entry design + color

Revision ID: 6277c2b64005
Revises: e37b0938e088
Create Date: 2026-06-10 21:43:40.819347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6277c2b64005'
down_revision: Union[str, None] = 'e37b0938e088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_entries', sa.Column('design_id', sa.Integer(), nullable=True))
    op.add_column('stage_entries', sa.Column('color_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_stage_entries_color_id_colors'), 'stage_entries', 'colors', ['color_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stage_entries_design_id_designs'), 'stage_entries', 'designs', ['design_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_stage_entries_design_id_designs'), 'stage_entries', type_='foreignkey')
    op.drop_constraint(op.f('fk_stage_entries_color_id_colors'), 'stage_entries', type_='foreignkey')
    op.drop_column('stage_entries', 'color_id')
    op.drop_column('stage_entries', 'design_id')
    # ### end Alembic commands ###
