"""machine_entry quantity + description

Revision ID: 8191ff693d9b
Revises: 81cfe16fc38e
Create Date: 2026-06-10 17:12:21.571747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8191ff693d9b'
down_revision: Union[str, None] = '81cfe16fc38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_entries', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('machine_entries', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine_entries', 'description')
    op.drop_column('machine_entries', 'quantity')
    # ### end Alembic commands ###
