"""users.username + multi-entry per stage

Revision ID: 81cfe16fc38e
Revises: 928020620750
Create Date: 2026-06-10 15:50:33.011137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cfe16fc38e'
down_revision: Union[str, None] = '928020620750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # A stage may now hold multiple entries per batch.
    op.drop_constraint('uq_stage_entries_batch_stage', 'stage_entries', type_='unique')

    # Add username: nullable first, backfill existing rows from the email local-part
    # (so existing accounts keep working), then enforce NOT NULL.
    op.add_column('users', sa.Column('username', sa.String(length=80), nullable=True))
    op.execute("UPDATE users SET username = split_part(email, '@', 1) WHERE username IS NULL")
    op.alter_column('users', 'username', existing_type=sa.String(length=80), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.create_unique_constraint('uq_stage_entries_batch_stage', 'stage_entries', ['batch_id', 'stage_id'])
    # ### end Alembic commands ###
