"""operations: batches, stage_entries, machine_entries, audit_log

Revision ID: 928020620750
Revises: 013b1b056308
Create Date: 2026-06-10 14:29:33.071393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '928020620750'
down_revision: Union[str, None] = '013b1b056308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_batches_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_stage_id'], ['stages.id'], name=op.f('fk_batches_current_stage_id_stages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_batches_template_id_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    op.create_index(op.f('ix_batches_code'), 'batches', ['code'], unique=True)
    op.create_index(op.f('ix_batches_template_id'), 'batches', ['template_id'], unique=False)
    op.create_table('stage_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_stage_entries_batch_id_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('fk_stage_entries_stage_id_stages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_stage_entries_submitted_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_entries')),
    sa.UniqueConstraint('batch_id', 'stage_id', name='uq_stage_entries_batch_stage')
    )
    op.create_index(op.f('ix_stage_entries_batch_id'), 'stage_entries', ['batch_id'], unique=False)
    op.create_index(op.f('ix_stage_entries_stage_id'), 'stage_entries', ['stage_id'], unique=False)
    op.create_table('machine_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_entry_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_entries_machine_id_machines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_machine_entries_operator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_entry_id'], ['stage_entries.id'], name=op.f('fk_machine_entries_stage_entry_id_stage_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_entries')),
    sa.UniqueConstraint('stage_entry_id', 'machine_id', name='uq_machine_entries_entry_machine')
    )
    op.create_index(op.f('ix_machine_entries_machine_id'), 'machine_entries', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_entries_stage_entry_id'), 'machine_entries', ['stage_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_entries_stage_entry_id'), table_name='machine_entries')
    op.drop_index(op.f('ix_machine_entries_machine_id'), table_name='machine_entries')
    op.drop_table('machine_entries')
    op.drop_index(op.f('ix_stage_entries_stage_id'), table_name='stage_entries')
    op.drop_index(op.f('ix_stage_entries_batch_id'), table_name='stage_entries')
    op.drop_table('stage_entries')
    op.drop_index(op.f('ix_batches_template_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_code'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
