"""batch_materials

Revision ID: a1e3746fd912
Revises: 8fcfa9bb0183
Create Date: 2026-06-10 21:20:49.403094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e3746fd912'
down_revision: Union[str, None] = '8fcfa9bb0183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_materials',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_materials_batch_id_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_batch_materials_inventory_item_id_inventory_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('batch_id', 'inventory_item_id', name=op.f('pk_batch_materials'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_materials')
    # ### end Alembic commands ###
