"""designs drop color_id

Revision ID: b706a7224c81
Revises: 6277c2b64005
Create Date: 2026-06-10 22:07:35.402279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b706a7224c81'
down_revision: Union[str, None] = '6277c2b64005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_designs_color_id_colors', 'designs', type_='foreignkey')
    op.drop_column('designs', 'color_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designs', sa.Column('color_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_designs_color_id_colors', 'designs', 'colors', ['color_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
