"""colors + designs

Revision ID: e37b0938e088
Revises: a1e3746fd912
Create Date: 2026-06-10 21:33:20.267687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37b0938e088'
down_revision: Union[str, None] = 'a1e3746fd912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hex', sa.String(length=9), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors'))
    )
    op.create_index(op.f('ix_colors_name'), 'colors', ['name'], unique=True)
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_designs_color_id_colors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_designs'))
    )
    op.create_index(op.f('ix_designs_name'), 'designs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designs_name'), table_name='designs')
    op.drop_table('designs')
    op.drop_index(op.f('ix_colors_name'), table_name='colors')
    op.drop_table('colors')
    # ### end Alembic commands ###
